version: '3'

services:
  rest-api-library:
    build: rest-api-library
    mem_limit: 512m
    ports:
      - "8081:8081"
    environment:
      DB_URL: jdbc:mysql://library:3306/library_api_db?createDatabaseIfNotExist=true
      DB_USER_NAME: root
      DB_PASSWORD: dim1913
    restart: always
    depends_on:
      library:
          condition: service_healthy
  library:
    image: mysql:8.0.33 
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: dim1913
      MYSQL_PASSWORD: dim1913
      MYSQL_DATABASE: library_api_db
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 10